#!/usr/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

#PYEXE=/data/alc/cchang/pyenv/rschenv/bin/python
PYEXE=/home/cchang/pyenv/rschenv/bin/python

$PYEXE $SCRIPT_DIR/arch.py $@

