region: apac  # Required: must match server's region for live mode
output_dir: ./outputs
log_dir: ./logs
# For replay, it will use historical_dir from this config
historical_dir: ./historical
historical_range:
  start: 2023-01-01
  end: 2023-12-31
replay_parallel: false
dataframe_types: [market_data]
